version: "3.7"
services:
  app:
      build:
        args:
          user: aji
          uid: 1000
        context: ./
        dockerfile: ./Dockerfile
      image: vlabnew
      container_name: vlabnew-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - vlabnew
  nginx:
    image: nginx:1.17-alpine
    container_name: vlabnew-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vlabnew
  vlabnewdb:
    image: mariadb:latest
    container_name: vlabnewdb
    ports:
      - 3306:3306
    volumes:
      - ./:/app_file
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      vlabnew:
        ipv4_address: 10.29.0.99
  phpmyadmin:
    image: phpmyadmin
    container_name: vlabnew-phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=vlabnewdb
      - PMA_PORT=3306
    networks:
      - vlabnew
volumes:
  mysql:
    driver: local
networks:
  vlabnew:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.29.0.0/24
            gateway: 10.29.0.1